version: 2
endpoint: https://control.westus2.azurecontainer.io:8080
metadata_directory: metadata
actions:
  kind: synchronous
  handler_webhook_baseurl: https://control.westus2.azurecontainer.io:3000
